### ISSUE TITLE
Problèem de calcul

### ISSUE THREAD

**Issue by crybouille** [njoyard/temposim#1]
Il y'a manifestement un soucis dans vos calculs, en faisant une simple opération kwh * tarif base on obtient des résultats différents de ceux présentés.
Par exemple pour une consommation de 11429.39 kwh, reparti comme suit : 
- 2023: 2499.63 kwh
- 2024: 8929.76 kwh

En base, votre appli donne : 
- 2023: 434.94€  alors que 2499.63 * 0.2276 = 568.92
- 2024: 1553.78€ alors que 8929.76 * 0.2512 = 2246.73

**Comment by njoyard** [comment]
Bonjour,

En effet, il y avait bien un bug lié à la sélection des tarifs (en l'occurrence, le calcul utilisait systématiquement les tarifs de février 2022...)

Le souci a été corrigé, je vous invite à vérifier. Assurez-vous bien que l'application est à jour (la version indiquée en bas de page doit être au moins 0.3.7, dans le cas contraire il faut forcer un rafraîchissement de la page).

Notez que pour votre vérification, le calcul sera de toute manière légèrement faux si vous le faites sur la consommation d'une année civile. En effet les tarifs changent chaque année au 1er février et au 1er août (sauf en 2024, pas de changement en août). Il faut faire ce calcul sur chaque mois et non chaque année.

Je vous remercie d'avoir remarqué ce problème, sans quoi je ne l'aurais vraisemblablement jamais vu...

**Comment by crybouille** [comment]
Merci pour votre réactivité 🙏
